version: '3.2'
services:
  author:
    image: author
    build: ./author
    ports:
      - "4502:4502"
    volumes:
      -  type: bind
         source: ./author/aem-logs/
         target: /opt/aem/crx-quickstart/logs/
    networks:
      - elk

  publish:
    image: publish
    build: ./publish
    ports:
      - "4503:4503"
    volumes:
      -  type: bind
         source: ./publish/aem-logs/
         target: /opt/aem/crx-quickstart/logs/
    networks:
      - elk

  dispatcher:
    image: dispatcher
    build: ./dispatcher
    ports:
      - "8080:80"
    depends_on:
      - "publish"
    networks:
      - elk

      # ElK Stack
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./publish/aem-logs/
        target: /usr/share/logstash/logs/publish/
        read_only: true
      - type: bind
        source: ./author/aem-logs/
        target: /usr/share/logstash/logs/author/
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: